---

- hosts: localhost
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Install Debian packages
      apt:
        name: "{{ packages.common + packages.linux_common + packages.ubuntu }}"
        state: latest
      become: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install RPM packages
      yum:
        name: "{{ packages.common + packages.linux_common + packages.centos }}"
        state: latest
      become: yes
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Install packages from MacOSX
      include_tasks: brew-packages.yaml
      when: ansible_distribution == 'MacOSX'

    - name: Install rust stable
      shell: cmd="sh <(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs) -y"
      args:
        creates: /home/amodm/.cargo/bin/rustup

