---

- hosts: localhost
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Install Debian packages
      apt:
        name: "{{ packages.common + packages.linux_common + packages.ubuntu }}"
        state: latest
      become: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install RPM packages
      yum:
        name: "{{ packages.common + packages.linux_common + packages.centos }}"
        state: latest
      become: yes
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Install packages from MacOSX
      import_tasks: brew-packages.yaml
      when: ansible_distribution == 'MacOSX'

    - name: Install rust stable
      shell:
        cmd: "sh <(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs) -y"
        creates: "{{ ansible_env.HOME }}/.cargo/bin/rustup"

    - name: Install oh-my-zsh
      shell:
        cmd: 'RUNZSH=no CHSH=no KEEPZSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
        creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

    - name: change default shell to zsh
      user:
        name: "{{ ansible_user }}"
        shell: /bin/zsh
      become: yes
